#!/usr/bin/env python3

from flask import Flask, request
import github3

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def handler():
    if request.method == "POST":
        print(request)
        return 'yes'
    else:
        return 'hey'

if __name__ == '__main__':
    app.run(port=27014, host='0.0.0.0', debug=True)
