#!/usr/bin/env python3

import flask
import github3

app = flask.Flask(__name__)

@app.route('/')
def handler():
    return 'Hello World!'

if __name__ == '__main__':
    app.run(port=9001, host='0.0.0.0')
