#!/usr/bin/env python3

import json

from flask import Flask, request, abort
from github3 import login
import github3

app = Flask(__name__)
gh = login('nixbot')

nicks = {'kragniz'}

class Nixbot:
    def __init__(self, webhookdata):
        self.data = webhookdata

        self.message = self.get_comment_body()
        self.user = self.get_comment_user()

        self.repo_owner, self.repo, self.pr_number = self.get_origin()

    def get_comment_body(self):
        return self.data.get('comment').get('body')

    def get_comment_user(self):
        return self.data.get('comment').get('user').get('login')

    def get_origin(self):
        owner, repository = self.data.get('repository').get('full_name').split('/')
        n = self.data.get('issue').get('number')
        return owner, repository, n

    def get_issue(self):
        issue = gh.issue(self.repo_owner, self.repo, self.pr_number)
        return issue

    def get_pull_request(self):
        issue = gh.issue(self.repo_owner, self.repo, self.pr_number)
        return issue

    def process(self):
        if self.user in nicks:
            if '@nixbot hello' in self.message:
                pr = self.get_issue()
                pr.create_comment('hi there @{}'.format(self.user))

@app.before_request
def limit_remote_addr():
    # whitelist github's ip
    if not request.remote_addr.startswith('192.30.252'):
        abort(403)

@app.route('/', methods=['GET', 'POST'])
def handler():
    if request.method == "POST":
        data = json.loads(request.data.decode('utf-8'))
        bot = Nixbot(data)
        bot.process()
        return 'yes'
    else:
        return 'no'

if __name__ == '__main__':
    app.run(port=9001, host='0.0.0.0', debug=True)
